service: catfecito-backend

frameworkVersion: "^4.0.0"

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN, '7d'}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_CLIENT_SECRET: ${env:COGNITO_CLIENT_SECRET, ''}
    S3_BUCKET: ${self:service}-products-${self:provider.stage}

  httpApi:
    authorizers: ${file(server/serverless-config/provider/httpApi.yml)}

  iam: 
    role: ${file(server/serverless-config/provider/iam.yml)}
    

functions:
  - ${file(server/serverless-config/functions/auth.yml)}
  - ${file(server/serverless-config/functions/users.yml)}
  - ${file(server/serverless-config/functions/admin.yml)}
  - ${file(server/serverless-config/functions/products.yml)}
  - ${file(server/serverless-config/functions/categories.yml)}
  - ${file(server/serverless-config/functions/cart.yml)}
  - ${file(server/serverless-config/functions/orders.yml)}
  

resources:
  - ${file(server/serverless-config/resources/dynamo.yml)}
  - ${file(server/serverless-config/resources/s3.yml)}
